### ISSUE TITLE
LOD Demo Not Working

### ISSUE THREAD

**Issue by igaln** [naver/egjs-view3d#1]
hello,

Cannot seem to get LOD demos loading, or maybe not sure what the expected behavior is
Tried both Safari 14.0, and Chrome 87, get stuck on loading mode

![image](https://user-images.githubusercontent.com/203732/101215430-ba52e380-3675-11eb-932c-703e2d01974c.png)

Excited to see this come to life.

**Comment by WoodNeck** [comment]
Hello, @igaln!
I found out that fetching those 3D model files from Github pages is being super slow.
Took 5min+ here with no problem on my internet connection, I should find out why.

**Comment by WoodNeck** [comment]
I guess there was a problem with Github pages, it just suddenly does work fine with my environment now.
Can you check it again? I hope it works.

**Comment by kenchikuliu** [comment]
> I guess there was a problem with Github pages, it just suddenly does work fine with my environment now.
> Can you check it again? I hope it works.

Hi, It also doesn‘t work in my ipad，same problem.

**Comment by WoodNeck** [comment]
@kenchikuliu 
Thanks for reporting :)
I think I have to change CDN for demo files. I'll leave a comment here when I'm done.

**Comment by kenchikuliu** [comment]
Could u please tell me the WallAR is based on webXR or something else？I wanna use it to build my own application.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Mingyu Kim<mailto:notifications@github.com>
发送时间: 2020年12月28日 18:00
收件人: naver/egjs-view3d<mailto:egjs-view3d@noreply.github.com>
抄送: kenchikuliu<mailto:kenchikuliu@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [naver/egjs-view3d] LOD Demo Not Working (#1)


@kenchikuliu<https://github.com/kenchikuliu>
Thanks for reporting :)
I think I have to change CDN for demo files. I'll leave a comment here when I'm done.

―

**Comment by WoodNeck** [comment]
@kenchikuliu 
WallARSession uses WebXR Device API, like FloorARSession and HoverARSession :)
Only SceneViewerSession and QuickLookSession do not use the WebXR API.
