### ISSUE TITLE
Error when building a react app

### ISSUE THREAD

**Issue by devhims** [naver/egjs-view3d#4]
First of all, great work guys! I read your medium posts and had to try out the library. 👏
I'm trying to integrate 3d view and ar features in my existing react project. But I'm getting the following error: 

```
index.js:1 SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at GLTFLoader.parse (GLTFLoader.js:213)
    at Object.onLoad (GLTFLoader.js:145)
    at XMLHttpRequest.<anonymous> (three.module.js:36216)
```
I've made a WebARTest component, then import and render it in App.js. This is how my code looks:

```
import View3D, { GLTFLoader } from '@egjs/view3d';
import React, { useRef, useEffect } from 'react';
import './viewstyles.css';

const WebARTest = () => {
  const canvasElement = useRef(null);

  useEffect(() => {
    const view3d = new View3D(canvasElement.current);
    const loader = new GLTFLoader();
    loader
      .load('./assets/specstand.glb')
      .then((model) => {
        view3d.display(model);
      })
      .catch((e) => {
        console.error(e);
      });
  }, [canvasElement]);

  return (
    <div id="view3d-wrapper">
      <canvas id="ar-canvas" ref={canvasElement}></canvas>
    </div>
  );
};

export default WebARTest;
```

I'm following the instruction listed on your tutorial page for [loading a model](https://naver.github.io/egjs-view3d/release/latest/docs/tutorial-Loading%20a%20Model.html).

**Comment by WoodNeck** [comment]
Hello @devhims!
By the error message, I guess there's something wrong with your 3D model.
JSON file usually starts with `{`, but looks like yours starts with `<`.

There's a useful site to test your GLTF/GLB model here :)
- https://github.khronos.org/glTF-Validator/

**Comment by devhims** [comment]
Thanks for the response @WoodNeck! Actually, there is no issue with the model file. I had to first import the model in the js file and then use it. 

`import spec from './assets/specstand.glb';`

then I used `spec` as an argument in the load method. While this technique works for .glb models, it didn't work for .gltf files. If you've any suggestions that would be awesome!! :)

**Comment by WoodNeck** [comment]
@devhims 
Hmm, in that case I assume that file is not loaded as a static file but in the format of a HTML page.
Check what it shows on the `./assets/specstand.glb` page and if it shows a HTML page, fix the config to serve static files on the assets folder.
In other way, moving the 3D model to the `public` folder will work I think.

**Comment by devhims** [comment]
@WoodNeck can you please share a link that explains how to update the config. As for moving the files to the public folder, react by default doesn't allow us to import assets from outside `src` directory.

**Comment by WoodNeck** [comment]
@devhims 
I hope this helps :)
https://create-react-app.dev/docs/using-the-public-folder/
See the `process.env.PUBLIC_URL` section

**Comment by devhims** [comment]
Thanks a bunch @WoodNeck! You're AWESOME!!
I'll most likely run into more issues as I continue to work on the library. I hope you don't mind me raising more issues. 😄

**Comment by WoodNeck** [comment]
@devhims 
I'm glad to hear that 👍 
Don't worry about filing more issues. I may be slow to respond if I'm working on other things, but I'll check yours soon as I can :)
