### ISSUE TITLE
Y axis cannot be moved

### ISSUE THREAD

**Issue by inTheSun** [naver/egjs-view3d#44]
## Description

On mobile phones, the model Y axis direction cannot be moved
## Steps to check or reproduce

Official website demo

**Comment by WoodNeck** [comment]
Scrolling vertically can trigger page scroll on mobile devices, and View3D won't change camera direction in that case.

By default, you can change the camera direction vertically by panning the model horizontally first, then vertically.
You can change this behavior by setting `scrollable` to false, but as the name suggests, the canvas area won't be scrollable.
- https://naver.github.io/egjs-view3d/docs/options/control/scrollable

If it's not the case, please leave the environment (device & browser) you use and I'll help.

**Comment by inTheSun** [comment]
> 

3Q
Your reply is very useful to me
