### ISSUE TITLE
Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json#overrides[0]': Cannot find module '@typescript-eslint/eslint-plugin'

### ISSUE THREAD

**Issue by RudyBlack** [naver/egjs-view3d#47]
<img width="1048" alt="Screen Shot 2022-11-20 at 5 40 25 PM" src="https://user-images.githubusercontent.com/21374353/202893303-6afca47b-449c-4fac-b41d-335ece2a9171.png">

The issue has been resolved after moving root file ".editorconfig", ".eslintrc.json" to packages/view3d.

**Comment by RudyBlack** [comment]
What should I do? It is alright to move file to there?

**Comment by WoodNeck** [comment]
Looks like I forgot to move some devDependencies from packages/view3d to root. I'll fix this.

**Comment by RudyBlack** [comment]
Thank you :)
