### ISSUE TITLE
Can I import glb files from memory into view3d?

### ISSUE THREAD

**Issue by easylogic** [naver/egjs-view3d#53]
## Description

I have a glb file in memory.

How can I apply this to the viewer?

## Steps to check or reproduce

Currently, I am setting the link as below.

```js
const glbFile = new window. Blob([glbBuffer], { type: "application/glb" });

const link = window.URL.createObjectURL(glbFile);

viewer3d.load(link);
```

## Problem 

When I create and apply the url in memory, the following error occurs.

```js
Uncaught (in promise) View3DError: Failed to load/parse the 3D model with the given url: "blob:https://test.domain/bebfeed4-24c8-4699-99f7-bda3929b7785". Check "loadError" event for actual error instance.
    at View3D.<anonymous> (view3d.esm.js:10010:15)
    at Generator.throw (<anonymous>)
    at rejected (view3d.esm.js:62:24)
```

**Comment by WoodNeck** [comment]
Hello, @easylogic!

I haven't tested such a case but it looks quite similar to how we're loading local files on our playground page.
Here's how we're loading local files (like dragging models into the page), I hope it helps.

```js
import { GLTFLoader } from "@egjs/view3d";

// fileMap: Map<string, any>
const files = Array.from(fileMap) as Array<[string, File]>;
const loader = new GLTFLoader(view3D);
const model = await loader.loadFromFiles(files.map(([name, file]) => file));

// Not necessary, so you can omit this
(view3D as any)._src = model.src;

view3D.display(model);
```

You can convert Blob to File like this:
```js
var file = new File([myBlob], "name");
```

**Comment by easylogic** [comment]
hi @WoodNeck  

i tested it with your sample code. 

But it is not working well. 

```js
const loader = new GLTFLoader(viewerRef.current);
const model = await loader.loadFromFiles([glbFile]);

viewerRef.current._src = model.src;

viewerRef.current.display(model);
```

Running the above code gives the following error.

<img width="785" alt="스크린샷 2022-12-29 오후 2 40 17" src="https://user-images.githubusercontent.com/591983/209908105-b79feec3-eae5-4969-a498-d31bb2a60812.png">

**Comment by WoodNeck** [comment]
Looks like the file itself contains nothing according to the error message.
Can you try:
1. Create a file from the buffer instead.
```js
const file = new File(glbBuffer, "name");
```

2. Use `three.js`'s GLTFLoader and use their `parse` instead (for testing)
```js
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

new GLTFLoader().parse(glbBuffer)
```
If this works, I'll add the `parse` binding for our `GLTFLoader` in the next version.

**Comment by easylogic** [comment]
The answer was late.
As you said last time, no error occurred in the parse() function of GLTFLoader.

And the current situation is a bit strange.
first 
```js
await viewerRef.current.load(glbFile);
```
 Loading is fine.
<img width="805" alt="스크린샷 2023-01-10 오전 12 19 15" src="https://user-images.githubusercontent.com/591983/211342736-029151be-4b0e-4401-a9b0-7f8968e3c459.png">

but from the second

The color of the model is not expressed normally.

<img width="835" alt="스크린샷 2023-01-10 오전 12 19 35" src="https://user-images.githubusercontent.com/591983/211342811-1c027fef-d29d-46da-b82a-cc58443461ec.png">

**Comment by easylogic** [comment]
@WoodNeck  

I designed the code badly.

The problem occurred because two view3d instances were applied to one canvas.

In conclusion, there is no problem with the library.

Also, calling the glb file with the load function works fine.

thanks for the nice code
