### ISSUE TITLE
Loading new 3D model / setting iosSrc

### ISSUE THREAD

**Issue by sir-oliver** [naver/egjs-view3d#57]
When I'm loading a new 3D model 

`view3D.load("new_model.usdz")`

I would like to change the "iosSrc" as well.

but `view3D.iosSrc = "new_model.usdz"` doesn't work.

How can I alter the iosSrc parameter?

Thanks in advance for your support!

**Comment by WoodNeck** [comment]
New API added in `v2.10.0`, try that one

**Comment by sir-oliver** [comment]
Works! Thanks a lot @WoodNeck!!
