### ISSUE TITLE
Canvas get's blank after applying/removing CSS 'display: none' to wrapper element

### ISSUE THREAD

**Issue by StefanThumann** [naver/egjs-view3d#60]
To show/hide the 3D viewer on a page I am using the CSS property "display: none" on the wrapper <div> container.

When removing the "display: none" attribute the canvas is blank white. Is there are workaround to this problem? Do I have to re-init the plugin in that case?

**Comment by WoodNeck** [comment]
Hello @StefanThumann.

This seems to be a bug in View3D.
If the canvas size goes to zero in any way, like setting its width to `0`, it seems like View3D can't render anymore.
I've also tried it with three.js, which is the backbone of View3D, and it doesn't seem to have the same issue, so there must be something wrong with our library logic.

I'll take a look at this issue.
Until a bug fix is released, you can use a CSS property like `visibility: hidden`, or you can set the size of the canvas to `1 * 1`.
Of course, in this case, you can use something like setting `position: absolute` on the container element to hide it from the layout.

**Comment by StefanThumann** [comment]
Using the CSS Class view3d-1by1 does make no difference. And the .view3d-canvas Class is has position absolute by default. The only thing that works is `visibilty: hidden`. 
Is there a way to re-init the plugin?

**Comment by WoodNeck** [comment]
Fixed in `v2.10.1`
