### ISSUE TITLE
I want to change the model during the XRSession.

### ISSUE THREAD

**Issue by littleanti** [naver/egjs-view3d#7]
Is it possible to change the model during the XRSession 
while locating a new model at the same location and fitting size of the new model at camera?

**Comment by littleanti** [comment]
For the experiment, I have used the ar-floor demo.

I added a button using DOM overlays. and linked a changeModel function to the button. 
In the changeModel function, I executed the below step by step.
1. I loaded the new model by using GLTFLoader().load.
2. After loading model, I called view3d.display(model...)

The code that I used is below.
`function changeModel() {
  var model_path = "<model_path>"+".glb"
  loader.load(model_path)
  .then(model => {
    view3d.display(model, {
      applySize: false,
      size: 100,
      resetView: false
    });
  });`

The video that is the result of my code.
https://user-images.githubusercontent.com/16498206/144455591-134c72dc-41df-452e-ae2f-a90dc359c99d.mp4

**Comment by littleanti** [comment]
When the new model was changed and displayed, the new model was located at camera origin, and I cannot control the new model.

**Comment by WoodNeck** [comment]
Hello @littleanti!
Try setting the old model's position into the new one's position.
Like,
```ts
const oldModel = view3d.model;
const oldModelPosition = oldModel.scene.position;

newModel.scene.position.copy(oldModelPosition);
// Adjust Y val by the size of model's bbox
newModel.scene.position.setY(newModel.scene.position + oldModel.bbox.min.y - newModel.bbox.min.y);

view3d.display(newModel, { applySize: false, resetView: false });
```

P.S.
We're preparing the next major version of this component right now.
I'll definitely make an API for this use case :)

**Comment by littleanti** [comment]
Thank you for reply. 

When I commented the below code, it works properly. 
`//newModel.scene.position.setY(newModel.scene.position + oldModel.bbox.min.y - newModel.bbox.min.y);`

By the way, after changing oldModel to newModel, the OrbitControl was broken, so I could not control loaded newModel.
How to restart model controller for newModel??

Thank you.
Yoon.

**Comment by WoodNeck** [comment]
@littleanti
I think maybe there's some issue with calculating the bounding box, I didn't check the actual model so I'm not sure about that though.
`_initModelPosition` should not be called again, as we're using the old model's position.
Was there an error when changing the model? Or, what exactly do you mean floor control is broken? Do you mean the model is just rotating wherever you click?

**Comment by littleanti** [comment]
https://user-images.githubusercontent.com/16498206/145138258-09c26d7e-7d27-42f8-b328-9f31e33065fb.mp4

In the video, I cannot control newModel after model changing.
I mean that AR controller does not work.

**Comment by WoodNeck** [comment]
Can you wait for me to release v2? I'll promise to include that feature in the next version.
v2 will be released within this month.

**Comment by littleanti** [comment]
I see! 
When the v2 will be opened, could u leave a comment to this thread?

**Comment by WoodNeck** [comment]
Sure, I'll do that :)

**Comment by littleanti** [comment]
Is there any update?

**Comment by WoodNeck** [comment]
@littleanti
It's almost done, and I'm working on the demos and documents. The estimated release date is this Friday :)

**Comment by WoodNeck** [comment]
@littleanti Hello!
I've just released a preview of the next version with the tag `next`.

You can install it like this:
```sh
npm i @egjs/view3d@next
```

Check the document & demo on here (I've also included the example of change model during AR session):
- https://woodneck.github.io/egjs-view3d/

**Comment by littleanti** [comment]
Thank you so much!..
I'd love this version 2!!
