### ISSUE TITLE
(Model preview) should support transparency

### ISSUE THREAD

**Issue by freder** [naver/egjs-view3d#8]
[three.js demo](https://threejs.org/examples/?q=gltf#webgl_loader_gltf_transmission) vs. this library

![image](https://user-images.githubusercontent.com/724844/145041454-532bdf38-9a83-4f3c-9b6c-9c6b9dbbbe8b.png)
![image](https://user-images.githubusercontent.com/724844/145041402-7e77edc9-8285-41c6-a883-684cbd658698.png)

**Comment by freder** [comment]
my assumption is that this is due to an old version of three.js being used here. so I tried using `GLTFLoader` and `DRACOLoader` from three.js directly:

```js
import View3D, {
	// GLTFLoader,
	// THREE,
	SceneViewerSession,
	QuickLookSession,
	Pose,
	AutoDirectionalLight,
	OrbitControl
} from '@egjs/view3d';
import { DRACOLoader } from '../node_modules/three/examples/jsm/loaders/DRACOLoader.js';
import { GLTFLoader } from '../node_modules/three/examples/jsm/loaders/GLTFLoader.js';


const loader = new GLTFLoader();
const dracoLoader = new DRACOLoader();
dracoLoader.setDecoderPath('/draco/gltf/');
// dracoLoader.setDecoderConfig({ type: 'js' });

// [...]
```

- with 0.116.x I get the same still
- from 0.120.x on I get: `THREE.MeshPhysicalMaterial: .transparency has been renamed to .transmission.`
- and for more current versions: `TypeError: decoder.GetAttributeDataArrayForAllPoints is not a function`

**Comment by freder** [comment]
for a workaround (not showing a model preview at all) – what would be the recommended way to use this library without having to initialize a `<canvas>`?

**Comment by WoodNeck** [comment]
Hello @freder!
Like you've suggested, I also think that cause is the old three.js version, as it didn't support `KHR_materials_transmission` extension of glTF.

Unfortunately, I think the only solution is updating the three.js version.
If that was just a tedious job, I would love to do it but as Three's interface is quite changed it can take a while to update.

But, we're about to release a new version within a month!
![image](https://user-images.githubusercontent.com/26213435/145131804-81d2833c-b343-48cd-adb8-25f5ed2e1f3a.png)
I've just tested that model using the same envmap (royal_esplanade_1k), and it works fine.
It can show a bit different color as I'm using LinearToneMapping here, while the Three's demo is using ACESFilmicToneMapping, but I'll make an option for this :)

**Comment by WoodNeck** [comment]
![image](https://user-images.githubusercontent.com/26213435/145132488-f0236d78-0fcf-4e10-9035-322d99f9fcb2.png)
> ACESFilmicToneMapping

**Comment by freder** [comment]
cool 👍
for now I simply built a basic model viewer in `three.js` directly.

> [...] what would be the recommended way to use this library without having to initialize a `<canvas>`?

that was easy enough. in case it's useful to someone else:

```js
import { SceneViewerSession, QuickLookSession } from '@egjs/view3d';
import { GLTFLoader } from '../node_modules/three/examples/jsm/loaders/GLTFLoader.js';


const loader = new GLTFLoader();
const sessions = [];


function addSession(session) {
	sessions.push(session);
}


async function enter() {
	for (let i = 0; i < sessions.length; i++) {
		const sess = sessions[i];
		const isAvailable = await sess.isAvailable();
		if (isAvailable) {
			return await sess.enter();
		}
	}
	throw new Error('Session not available');
}


loader.load(modelPathGltf, (model) => {
	// ...
});

// android
addSession(new SceneViewerSession({
	file: new URL(modelPathGltf, location.href).href,
	title: modelTitle,
	link: modelPathGltf,
	resizable: false,
	mode: 'ar_only'
}));

// ios
addSession(new QuickLookSession({
	file: new URL(modelPathUsdz, location.href).href,
}));
```

**Comment by WoodNeck** [comment]
@freder Hello!
I've just released a preview of the next version with the tag `next`.

You can install it like this:
```sh
npm i @egjs/view3d@next
```

Check the document & demo on here:
- https://woodneck.github.io/egjs-view3d/

That model is also tested :)
![image](https://user-images.githubusercontent.com/26213435/147812889-68c36648-ca84-4240-842a-932eb9908a68.png)

**Comment by freder** [comment]
> [...] what would be the recommended way to use this library without having to initialize a <canvas>?

currently looking into the same thing again, but with the latest version of this library...

**Comment by WoodNeck** [comment]
@freder 
Hi, what is the feature you are looking for?
Is it possible to solve it with [autoInit](https://naver.github.io/egjs-view3d/docs/options/miscellaneous/autoInit)?
